development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Project-Alpha_development
  pool: 5
  username: mysql
  password: 'root'
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Project-Alpha_test
  pool: 5
  username: mysql
  password: 'root'
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Project-Alpha_production
  pool: 5
  username: mysql
  password: 'root'
  socket: /tmp/mysql.sock
